name: Build

on:
  # push:
  workflow_dispatch:
    # branches:
    #   - main
    # paths:
    #   - 'transformation_query/**'
# permissions:
#   contents: read
#   pages: write

env:
  ACTIONS_RUNNER_DEBUG: true
  snow_user: ${{ secrets.SNOW_USER }}
  snow_pwd: ${{ secrets.SNOW_PASSWORD }}
  snow_acc: ${{ secrets.SNOW_ACCOUNT }}

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix: 
        os: [windows-latest]
        python-version:
          - "3.10"
    
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest -v

      - name: Run Variable File
        run: python vars.py
      
      - name: Run Schemachange
        env:
          ACTIONS_RUNNER_DEBUG: true
          SF_ACCOUNT: ${{ secrets.SNOW_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SNOW_USER }}
          SF_ROLE: ${{ env.ROLE }}
          SF_WAREHOUSE: ${{ env.WAREHOUSE }}
          SF_DATABASE: ${{ env.DB }}
          SF_DEPLOY_DATABASE: ${{ env.DEPLOY_DB }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          echo "SF_ACCOUNT:  ${{ secrets.SNOW_ACCOUNT }}"
          echo "SF_USERNAME: ${{ secrets.SNOW_USER }}"

          schemachange -f $GITHUB_WORKSPACE/schema_change \
                       -a ${{ secrets.SNOW_ACCOUNT }} -u ${{ secrets.SNOW_USER }} \
                       -u ${{ secrets.SNOW_USER }} \
                       -r ${{ env.ROLE }} \
                       -w ${{ env.WAREHOUSE }} \
                       -d ${{ env.DEPLOY_DB }} \
                       -c ${{ env.DEPLOY_DB }}.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table

          
# schemachange -f $GITHUB_WORKSPACE/schema_change -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DEPLOY_DATABASE -c $SF_DEPLOY_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
